### ISSUE TITLE
Error connecting to yubikey in init

### ISSUE THREAD

**Issue by Johbii** [whinis/keechallenge#3]
Recieving "Error connecting to yubikey in init!" with user challenge mode.

Yubikey settings
-Slot 2
-HMAC-SHA1 (non-variable length 64 byte)
-Require user input

I tried with "Require user input" enabled and disabled to the same effect.
I am using the YubiKey 5Ci (USB C)

**Comment by whinis** [comment]
Can you try the new PLGX I just updated the 1.7 release to. I also marked it as a pre-release. 
It seems the auto detect is not working and I need to check that so try forcing the slot to slot 2.

**Comment by Johbii** [comment]
Working now as intended, thanks.

**Comment by whinis** [comment]
If its on auto-select it should just work but I think it broke with the 5 series. I am looking at fixing it as soon as I can figure out what broke

**Comment by Johbii** [comment]
Just checked, auto-select IS working for my Yubikey.

**Comment by whinis** [comment]
Is yours set to slot 1? It defaults to slot 1 if none is detected

**Comment by Johbii** [comment]
Mine is slot 2

**Comment by whinis** [comment]
Interesting, what Yubikey do you have ?
